# Makefile — LARA compiler (Stage 1: frontend)
#
# Usage:
#   make           — build ./lara
#   make clean     — remove generated files
#   make test      — run tests/
#   make ast       — build and print the AST for a sample program

TARGET = lara
SRCDIR = src

CC      = gcc
CFLAGS  = -Wall -Wextra -g -std=c11 -D_POSIX_C_SOURCE=200809L -I$(SRCDIR)

FLEX    = flex
BISON   = bison

# Generated by flex/bison — do not edit directly
BISON_OUT  = $(SRCDIR)/parser.tab.c
BISON_H    = $(SRCDIR)/parser.tab.h
FLEX_OUT   = $(SRCDIR)/lex.yy.c

C_SRCS = $(SRCDIR)/ast.c \
         $(SRCDIR)/symtab.c \
         $(SRCDIR)/ast_walk.c \
         $(SRCDIR)/main.c

ALL_SRCS = $(BISON_OUT) $(FLEX_OUT) $(C_SRCS)
OBJS = $(ALL_SRCS:.c=.o)

UNAME := $(shell uname)
ifeq ($(UNAME),Darwin)
    # works around a flex/PATH-length bug on macOS
    FLEX_ENV = env -i PATH="/usr/bin:/bin:/usr/local/bin:/opt/homebrew/bin" \
               HOME="$${HOME}" TMPDIR="$${TMPDIR}" LANG="C"
else
    FLEX_ENV =
endif

.PHONY: all clean test ast help

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^
	@echo ">>> Compilação concluída: $(TARGET)"

# bison must run before flex — it produces parser.tab.h, which scanner.l needs
$(BISON_OUT) $(BISON_H): $(SRCDIR)/parser.y
	$(BISON) -d -o $(BISON_OUT) $(SRCDIR)/parser.y
	@echo ">>> bison gerou $(BISON_OUT) e $(BISON_H)"

$(FLEX_OUT): $(SRCDIR)/scanner.l $(BISON_H)
	$(FLEX_ENV) $(FLEX) -o $(FLEX_OUT) $(SRCDIR)/scanner.l
	@echo ">>> flex gerou $(FLEX_OUT)"

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

$(SRCDIR)/lex.yy.o:     $(FLEX_OUT) $(BISON_H) $(SRCDIR)/tokens.h $(SRCDIR)/symtab.h $(SRCDIR)/ast.h
$(SRCDIR)/parser.tab.o: $(BISON_OUT) $(BISON_H) $(SRCDIR)/ast.h $(SRCDIR)/symtab.h
$(SRCDIR)/ast.o:        $(SRCDIR)/ast.c $(SRCDIR)/ast.h
$(SRCDIR)/symtab.o:     $(SRCDIR)/symtab.c $(SRCDIR)/symtab.h
$(SRCDIR)/ast_walk.o:   $(SRCDIR)/ast_walk.c $(SRCDIR)/ast.h
$(SRCDIR)/main.o:       $(SRCDIR)/main.c $(SRCDIR)/ast.h $(SRCDIR)/symtab.h

clean:
	rm -f $(SRCDIR)/lex.yy.c $(SRCDIR)/parser.tab.c $(SRCDIR)/parser.tab.h
	rm -f $(SRCDIR)/*.o
	rm -f $(TARGET)
	@echo ">>> Limpeza concluída."

test: $(TARGET)
	@echo "=== Testes de programas VÁLIDOS ==="
	@passed=0; failed=0; \
	for f in tests/valid/*.lc; do \
	    printf "  %-40s " "$$f"; \
	    if ./$(TARGET) < "$$f" > /dev/null 2>&1; then \
	        echo "OK"; passed=$$((passed+1)); \
	    else \
	        echo "FALHOU"; failed=$$((failed+1)); \
	    fi; \
	done; \
	echo "  Resultado: $$passed OK, $$failed FALHOU"
	@echo ""
	@echo "=== Testes de programas INVÁLIDOS (devem falhar) ==="
	@passed=0; failed=0; \
	for f in tests/invalid/*.lc; do \
	    printf "  %-40s " "$$f"; \
	    if ./$(TARGET) < "$$f" > /dev/null 2>&1; then \
	        echo "DEVERIA TER FALHADO (erro!)"; failed=$$((failed+1)); \
	    else \
	        echo "Rejeitado (correto)"; passed=$$((passed+1)); \
	    fi; \
	done; \
	echo "  Resultado: $$passed rejeitados corretamente, $$failed com problema"

ast: $(TARGET)
	@echo "=== AST do programa de exemplo ==="
	./$(TARGET) < tests/valid/01_hello.lc

help:
	@echo "Alvos disponíveis:"
	@echo "  make         — compila e gera ./lara"
	@echo "  make clean   — remove arquivos gerados"
	@echo "  make test    — executa suite de testes"
	@echo "  make ast     — mostra AST do exemplo básico"
	@echo "  make help    — exibe esta mensagem"
