# Makefile — LARA compiler (Stage 2: basic TAC)
#
# Usage:
#   make           — build ./lara
#   make clean     — remove generated files
#   make test      — run tests/
#   make ast       — build and print the AST for a sample program

TARGET = lara
SRCDIR = src

CC      = gcc
CFLAGS  = -Wall -Wextra -g -std=c11 -D_POSIX_C_SOURCE=200809L -I$(SRCDIR)

FLEX    = flex
BISON   = bison
PYTHON  = python3
FILE ?= tests/valid/01_soma.lc

# Generated by flex/bison — do not edit directly
BISON_OUT  = $(SRCDIR)/parser.tab.c
BISON_H    = $(SRCDIR)/parser.tab.h
FLEX_OUT   = $(SRCDIR)/lex.yy.c

C_SRCS = $(SRCDIR)/ast.c \
         $(SRCDIR)/symtab.c \
         $(SRCDIR)/ast_walk.c \
         $(SRCDIR)/tac.c \
         $(SRCDIR)/codegen.c \
         $(SRCDIR)/main.c

ALL_SRCS = $(BISON_OUT) $(FLEX_OUT) $(C_SRCS)
OBJS = $(ALL_SRCS:.c=.o)

UNAME := $(shell uname)
ifeq ($(UNAME),Darwin)
    # works around a flex/PATH-length bug on macOS
    FLEX_ENV = env -i PATH="/usr/bin:/bin:/usr/local/bin:/opt/homebrew/bin" \
               HOME="$${HOME}" TMPDIR="$${TMPDIR}" LANG="C"
else
    FLEX_ENV =
endif

COMPOSE = docker compose -f docker/docker-compose.yml

.PHONY: all clean test test-memory ast ast-dot help docker-build docker-shell docker-test docker-ast package

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^
	@echo ">>> Compilação concluída: $(TARGET)"

# bison must run before flex — it produces parser.tab.h, which scanner.l needs
$(BISON_OUT) $(BISON_H) &: $(SRCDIR)/parser.y
	$(BISON) -d -o $(BISON_OUT) $(SRCDIR)/parser.y
	@echo ">>> bison gerou $(BISON_OUT) e $(BISON_H)"

$(FLEX_OUT): $(SRCDIR)/scanner.l $(BISON_H)
	$(FLEX_ENV) $(FLEX) -o $(FLEX_OUT) $(SRCDIR)/scanner.l
	@echo ">>> flex gerou $(FLEX_OUT)"

%.o: %.c
	$(CC) $(CFLAGS) -c -o $@ $<

$(SRCDIR)/lex.yy.o:     $(FLEX_OUT) $(BISON_H) $(SRCDIR)/tokens.h $(SRCDIR)/symtab.h $(SRCDIR)/ast.h
$(SRCDIR)/parser.tab.o: $(BISON_OUT) $(BISON_H) $(SRCDIR)/ast.h $(SRCDIR)/symtab.h
$(SRCDIR)/ast.o:        $(SRCDIR)/ast.c $(SRCDIR)/ast.h
$(SRCDIR)/symtab.o:     $(SRCDIR)/symtab.c $(SRCDIR)/symtab.h
$(SRCDIR)/ast_walk.o:   $(SRCDIR)/ast_walk.c $(SRCDIR)/ast.h
$(SRCDIR)/tac.o:        $(SRCDIR)/tac.c $(SRCDIR)/tac.h
$(SRCDIR)/codegen.o:    $(SRCDIR)/codegen.c $(SRCDIR)/codegen.h $(SRCDIR)/tac.h $(SRCDIR)/ast.h $(SRCDIR)/symtab.h
$(SRCDIR)/main.o:       $(SRCDIR)/main.c $(SRCDIR)/ast.h $(SRCDIR)/symtab.h $(SRCDIR)/codegen.h $(SRCDIR)/tac.h

CORE_OBJS = $(filter-out $(SRCDIR)/main.o,$(OBJS))
TEST_CORE = tests/core_tests

$(TEST_CORE): tests/test_core.c $(CORE_OBJS) $(SRCDIR)/ast.h $(SRCDIR)/symtab.h $(SRCDIR)/codegen.h $(SRCDIR)/tac.h
	$(CC) $(CFLAGS) -o $@ tests/test_core.c $(CORE_OBJS)

clean:
	rm -f $(SRCDIR)/lex.yy.c $(SRCDIR)/parser.tab.c $(SRCDIR)/parser.tab.h
	rm -f $(SRCDIR)/*.o
	rm -f $(TARGET) $(TEST_CORE)
	@echo ">>> Limpeza concluída."

test: $(TARGET) $(TEST_CORE)
	@bash tests/run_tests.sh "./$(TARGET)"
	@./$(TEST_CORE)

test-memory: $(TARGET) $(TEST_CORE)
	$(PYTHON) tests/test_memory.py "./$(TARGET)" "./$(TEST_CORE)"

ast: $(TARGET)
	@echo "=== AST do programa de exemplo ==="
	./$(TARGET) --ast < "$(FILE)"

## Renders the AST of FILE as Graphviz .dot (and .svg if graphviz is installed)
## Usage: make ast-dot FILE=tests/valid/01_soma.lc
ast-dot: $(TARGET)
	@bash -o pipefail -c './$(TARGET) --ast < "$(FILE)" | $(PYTHON) tools/ast_to_dot.py > ast.dot'
	@command -v dot >/dev/null 2>&1 && dot -Tsvg ast.dot -o ast.svg && echo ">>> ast.dot e ast.svg gerados" || echo ">>> ast.dot gerado (graphviz não encontrado para gerar .svg)"

docker-build:
	$(COMPOSE) build

docker-shell:
	$(COMPOSE) run --rm dev bash

docker-test:
	$(COMPOSE) run --rm dev make test

docker-ast:
	$(COMPOSE) run --rm dev make ast

package:
	$(PYTHON) tools/package_stage.py --stage 2

help:
	@echo "Alvos disponíveis:"
	@echo "  make              — compila e gera ./lara"
	@echo "  make clean        — remove arquivos gerados"
	@echo "  make test         — executa suite de testes"
	@echo "  make test-memory  — verifica memória com Valgrind"
	@echo "  make package      — gera e valida ZIP e tar.gz da etapa atual"
	@echo "  make ast          — mostra AST do exemplo básico"
	@echo "  make ast-dot      — gera ast.dot (e ast.svg) para FILE=<arquivo.lc>"
	@echo "  make docker-build — constrói a imagem de desenvolvimento"
	@echo "  make docker-shell — abre um shell dentro do container"
	@echo "  make docker-test  — roda 'make test' dentro do container"
	@echo "  make docker-ast   — roda 'make ast' dentro do container"
	@echo "  make help         — exibe esta mensagem"
